### ISSUE TITLE
Write Instructions For Deploying CSKnow Server (And Create Discord For People Running/Playing On The Servers)

### ISSUE THREAD

**Issue by David-Durst** [David-Durst/csknow#3]
Please add a +1 if you want me to work on this.

**Comment by manicogaming** [comment]
+1

**Comment by RichOnPeers** [comment]
+1

**Comment by ElvinEnchant** [comment]
+1

**Comment by tinygrox** [comment]
+1

**Comment by David-Durst** [comment]
Hey everyone, sorry for the delay! I still haven't gotten to this yet. I prioritized creating the learned mouse controller first (#4). I was hoping to both (a) have you test the servers and (b) give you a cool new mouse controller to play with. However, that is taking longer than expected. Some basic issues have been fixed (like accurately finding head position https://davidbdurst.com/blog/csknow_head_position.html) and some more complicated issues are still outstanding (like accounting for the related literature on mouse movement https://dl.acm.org/doi/10.1145/3411764.3445514, https://arxiv.org/pdf/2203.12050.pdf). I will get this issue (#3) done soon!

**Comment by ElvinEnchant** [comment]
Take your time! You're doing awesome work, man!

**Comment by David-Durst** [comment]
Here are the instructions for playing against the bots. https://github.com/David-Durst/csknow/blob/master/docs/bot_user_instructions.md

If you don't have a linux machine to run the bots, I also wrote instructions for creating an AWS machine that can host the bots: https://github.com/David-Durst/csknow/blob/master/docs/aws_machine_creation_guide.md

Before I close the issue, can someone confirm that the bot user instructions work for them?

My next step is to write the dev guide so you all can mess around with my analytics, like this which shows player's position, mouse speed, and mouse delta relative to enemy head position over time:  https://youtu.be/ugwdOI9RpFs These visualizations (and the models using the data in the visualizations) are my main focus right now.

**Comment by David-Durst** [comment]
https://discord.gg/zWTDgabxr9 is the link for the CSKnow discord

**Comment by David-Durst** [comment]
Here is the dev guide for setting up the analytics environment (not needed to play with bots, but can be interesting to look at pro data) https://github.com/David-Durst/csknow/blob/master/docs/dev_setup_guide.md

**Comment by tinygrox** [comment]
😁

**Comment by schalkburger** [comment]
+1
